version: '3.3'
services:
  mein-blog-gk:
    build: .
    image: blog/gk:latest
    ports:
      - "8080:8080"
      - "9990:9990"
      - "2223:22"
    links:
      - db
    environment:
      DEBUG: 'true'
  db:
    image: mysql:8.0.11
    volumes:
      - db_data:/var/lib/mysql
    ports:
    - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: meinbloggk
      
volumes:
      db_data: