version: '3'
services:
  db:
    build: ./Docker_DB .
    image: blog/db:latest
    ports:
    - "3308:3306"
  mein-blog-gk:
    depends_on:
    - db
    build: .
    image: blog/gk:latest
    ports:
      - "8080:8080"
    environment:
      DEBUG: 'true'
